// Nouveautés 2025-2026. Prix indicatifs en FCFA : à ajuster selon vos arrivages.
// Photos : Wikimedia Commons, voir src/data/imageCredits.json
const img = (file) => `/images/produits/2026/${file}`;

const products2026 = [
  // ---------- TÉLÉPHONES ----------
  {
    name: "iPhone 18 Pro Max",
    category: "phones",
    brand: "Apple",
    price: "1 350 000",
    image: img("iphone-18-pro-max.jpg"),
    badge: "Nouveau 2026",
    badgeColor: "bg-black",
    stock: "Sur commande",
    warranty: "12 mois",
    features: ["Puce A20 Pro (2 nm)", "Écran 6.9\"", "Caméra 48MP ouverture variable", "Jusqu'à 2 To"],
  },
  {
    name: "iPhone 18 Pro",
    category: "phones",
    brand: "Apple",
    price: "1 200 000",
    image: img("iphone-18-pro.jpg"),
    badge: "Nouveau 2026",
    badgeColor: "bg-black",
    stock: "Sur commande",
    warranty: "12 mois",
    features: ["Puce A20 Pro (2 nm)", "Écran 6.3\"", "Caméra 48MP ouverture variable", "256 Go minimum"],
  },
  {
    name: "iPhone 17 Pro Max",
    category: "phones",
    brand: "Apple",
    price: "1 100 000",
    oldPrice: "1 200 000",
    image: img("iphone-17-pro-max.png"),
    badge: "Populaire",
    badgeColor: "bg-blue-600",
    stock: "En stock",
    warranty: "12 mois",
    features: ["Puce A19 Pro", "Écran 6.9\" ProMotion", "Triple caméra 48MP", "Châssis aluminium"],
  },
  {
    name: "iPhone 17 Pro",
    category: "phones",
    brand: "Apple",
    price: "950 000",
    oldPrice: "1 050 000",
    image: img("iphone-17-pro.jpg"),
    stock: "En stock",
    warranty: "12 mois",
    features: ["Puce A19 Pro", "Écran 6.3\" ProMotion", "Triple caméra 48MP", "Zoom 8x qualité optique"],
  },
  {
    name: "iPhone Air",
    category: "phones",
    brand: "Apple",
    price: "850 000",
    image: img("iphone-air.jpg"),
    badge: "Ultra-fin",
    badgeColor: "bg-sky-500",
    stock: "En stock",
    warranty: "12 mois",
    features: ["5,6 mm d'épaisseur", "Puce A19 Pro", "Écran 6.5\" ProMotion", "Caméra 48MP"],
  },
  {
    name: "iPhone 17",
    category: "phones",
    brand: "Apple",
    price: "700 000",
    image: img("iphone-17.jpg"),
    stock: "En stock",
    warranty: "12 mois",
    features: ["Puce A19", "Écran 6.3\" ProMotion 120Hz", "256 Go minimum", "Caméra avant 18MP Center Stage"],
  },
  {
    name: "Samsung Galaxy S26 Ultra",
    category: "phones",
    brand: "Samsung",
    price: "1 050 000",
    image: img("galaxy-s26-ultra.jpg"),
    badge: "Galaxy AI",
    badgeColor: "bg-indigo-600",
    stock: "En stock",
    warranty: "12 mois",
    features: ["Caméra 200MP", "Écran Privacy Display", "S Pen intégré", "Téléobjectif 50MP"],
  },
  {
    name: "Samsung Galaxy Z Fold7",
    category: "phones",
    brand: "Samsung",
    price: "1 300 000",
    image: img("galaxy-z-fold7.jpg"),
    badge: "Pliable",
    badgeColor: "bg-purple-600",
    stock: "Sur commande",
    warranty: "12 mois",
    features: ["Écran pliable 8\"", "Caméra 200MP", "Galaxy AI", "Format ultra-fin"],
  },
  {
    name: "Google Pixel 11 Pro",
    category: "phones",
    brand: "Google",
    price: "800 000",
    image: img("pixel-11-pro.png"),
    badge: "Nouveau 2026",
    badgeColor: "bg-emerald-600",
    stock: "Sur commande",
    warranty: "12 mois",
    features: ["Gemini intégré", "Mode Nuit avancé", "7 ans de mises à jour", "Triple caméra"],
  },
  {
    name: "Xiaomi 17 Ultra",
    category: "phones",
    brand: "Xiaomi",
    price: "1 000 000",
    image: img("xiaomi-17-ultra.jpg"),
    badge: "Leica",
    badgeColor: "bg-red-600",
    stock: "Sur commande",
    warranty: "12 mois",
    features: ["Optiques Leica", "Batterie 6000 mAh", "Charge ultra-rapide", "Écran AMOLED"],
  },
  {
    name: "Samsung Galaxy A56 5G",
    category: "phones",
    brand: "Samsung",
    price: "250 000",
    image: img("galaxy-a56.jpg"),
    badge: "Meilleur prix",
    badgeColor: "bg-green-600",
    stock: "En stock",
    warranty: "12 mois",
    features: ["Écran 6.7\" 120Hz", "Batterie 5000 mAh", "5G", "6 ans de mises à jour"],
  },
  {
    name: "Redmi Note 14 Pro",
    category: "phones",
    brand: "Xiaomi",
    price: "180 000",
    image: img("redmi-note-14-pro.jpg"),
    stock: "En stock",
    warranty: "12 mois",
    features: ["Caméra 200MP", "Écran AMOLED 120Hz", "Grande batterie", "Charge rapide"],
  },
  {
    name: "Tecno Camon 40 Pro 5G",
    category: "phones",
    brand: "Tecno",
    price: "160 000",
    image: img("tecno-camon-40-pro.jpg"),
    stock: "En stock",
    warranty: "12 mois",
    features: ["5G", "Écran AMOLED", "Caméra 50MP", "Charge rapide"],
  },
  {
    name: "Infinix Note 50 Pro",
    category: "phones",
    brand: "Infinix",
    price: "140 000",
    image: img("infinix-note-50-pro.jpg"),
    stock: "En stock",
    warranty: "12 mois",
    features: ["Écran AMOLED", "Charge rapide", "Grande batterie", "Design premium"],
  },

  // ---------- ORDINATEURS ----------
  {
    name: "MacBook Air 13\" M5",
    category: "computers",
    brand: "Apple",
    price: "850 000",
    image: img("macbook-air-m5.jpg"),
    badge: "Nouveau 2026",
    badgeColor: "bg-black",
    stock: "En stock",
    warranty: "12 mois",
    features: ["Puce Apple M5", "16 Go RAM", "Écran Liquid Retina 13.6\"", "Silencieux (sans ventilateur)"],
  },
  {
    name: "MacBook Pro 14\" M5",
    category: "computers",
    brand: "Apple",
    price: "1 250 000",
    image: img("macbook-pro-m5.jpg"),
    badge: "Pro",
    badgeColor: "bg-blue-600",
    stock: "Sur commande",
    warranty: "12 mois",
    features: ["Puce Apple M5", "16 Go RAM", "Écran Liquid Retina XDR", "Autonomie longue durée"],
  },
  {
    name: "HP Victus 15 Gaming",
    category: "computers",
    brand: "HP",
    price: "650 000",
    image: img("hp-victus-15.jpg"),
    badge: "Gaming",
    badgeColor: "bg-red-600",
    stock: "En stock",
    warranty: "12 mois",
    features: ["Carte graphique NVIDIA RTX", "16 Go RAM", "SSD 512 Go", "Écran 144Hz"],
  },
  {
    name: "Dell XPS 14 (2026)",
    category: "computers",
    brand: "Dell",
    price: "1 150 000",
    image: "/images/produits/pc-generic.jpg",
    stock: "Sur commande",
    warranty: "12 mois",
    features: ["Intel Core Ultra", "16 Go LPDDR5X", "SSD 512 Go", "Graphiques Intel Arc"],
  },

  // ---------- TABLETTES ----------
  {
    name: "iPad Pro 11\" M5",
    category: "tablets",
    brand: "Apple",
    price: "900 000",
    image: img("ipad-pro-m5.jpg"),
    badge: "Nouveau",
    badgeColor: "bg-black",
    stock: "Sur commande",
    warranty: "12 mois",
    features: ["Puce Apple M5", "Écran OLED Ultra Retina XDR", "Compatible Apple Pencil Pro", "Ultra-fin"],
  },
  {
    name: "iPad Air 11\" M3",
    category: "tablets",
    brand: "Apple",
    price: "550 000",
    image: img("ipad-air-m3.jpg"),
    stock: "En stock",
    warranty: "12 mois",
    features: ["Puce Apple M3", "Écran Liquid Retina 11\"", "Apple Intelligence", "Touch ID"],
  },
  {
    name: "Samsung Galaxy Tab S10 Ultra",
    category: "tablets",
    brand: "Samsung",
    price: "850 000",
    image: img("galaxy-tab-s10-ultra.png"),
    stock: "Sur commande",
    warranty: "12 mois",
    features: ["Écran AMOLED 14.6\"", "S Pen inclus", "Galaxy AI", "Idéal travail & dessin"],
  },

  // ---------- ACCESSOIRES ----------
  {
    name: "AirPods Pro 3",
    category: "accessories",
    brand: "Apple",
    price: "220 000",
    image: img("airpods-pro-3.jpg"),
    badge: "Nouveau",
    badgeColor: "bg-black",
    stock: "En stock",
    warranty: "12 mois",
    features: ["Réduction de bruit active", "Capteur de fréquence cardiaque", "Traduction en direct", "Résistants à l'eau"],
  },
];

module.exports = { products2026 };
